sudo: false
node_js:
- 6
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.yarn-cache
install: 
  npm install -g yarn && yarn
script:
  - npm run lint
  - npm run build-dev
after_script:
  - npm run test